namespace CMCS.Models
{
    public class ErrorViewModel
    {
        //Auto generated by VS
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}
